spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:44578/railway
spring.datasource.username=root
spring.datasource.password=FztyvaPmBoAaUMmZzpedEioyJuPgGvlf

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
	
server.port=${PORT:8000}

cloudinary.cloud_name=dztkarhax
cloudinary.api_key=953128619141896
cloudinary.api_secret=x3GDb6cODzSTxBzdRj6ePXt6YHg